services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: notes_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
